configuration:
  runtime: "concord-v2"
# flows:
#   main:
#     - log: "Hello World"


flows:
  default:
    - log: "Hello World"
    - task: http
      in:
        url: "https://google.com"
      out: result

    - if: ${not result.ok}
      then:
        - log: "task failed: ${result.error}"

